### ISSUE TITLE
mysql version?

### ISSUE THREAD

**Issue by zhixuqiu** [UcarLab/QuIN#1]
I want to install QuIN in my computer refer your setupguide document. However, the mysql database didn't load my data . Could you tell me the version of  mysql which you used in QuIN?

**Comment by ajt986** [comment]
I've been running a 5.6.19 MySQL Community Server (GPL) for my local instance of QuIN. 

Let me know if you're still having issues loading your data and any additional details you may have.

**Comment by zhixuqiu** [comment]
> I've been running a 5.6.19 MySQL Community Server (GPL) for my local instance of QuIN.
> 
> Let me know if you're still having issues loading your data and any additional details you may have.
OK, thanks for your help. Althought I have installed 5.6.19 MYSQL, I still didn't load my data when I run java packages, such as "UCSCRefFlatImport.jar", and there are no error outputed.  Could you share your java source code, “context.xml” file from tomcat or other important parameters? My E-mail is zhixuqiu@nwsuaf.edu.cn.

**Comment by ajt986** [comment]
[ImportCode.zip](https://github.com/UcarLab/QuIN/files/2616068/ImportCode.zip)
[context.xml.zip](https://github.com/UcarLab/QuIN/files/2616085/context.xml.zip)
It seems like the import tool may not be reading the file correctly.  I've attached the code for all the import tools as well as the context.xml file. Let me know if the code was of any help.

**Comment by zhixuqiu** [comment]
> [ImportCode.zip](https://github.com/UcarLab/QuIN/files/2616068/ImportCode.zip)
> [context.xml.zip](https://github.com/UcarLab/QuIN/files/2616085/context.xml.zip)
> It seems like the import tool may not be reading the file correctly. I've attached the code for all the import tools as well as the context.xml file. Let me know if the code was of any help.

thanks for yours help! I will try again.
